.TH MYSTRNCPY 3 "2025-09-22" "libmyutils" "Utility Functions"
.SH NAME
mystrncpy \- Copy a limited number of characters from a string
.SH SYNOPSIS
.B int mystrncpy(char* dest, const char* src, int n);
.SH DESCRIPTION
Copies up to n characters from src to dest, adding a null terminator if src is shorter. Returns the number of characters copied.
.SH AUTHOR
Muneeb <muneeb@example.com>