.TH MYSTRCAT 3 "2025-09-22" "libmyutils" "Utility Functions"
.SH NAME
mystrcat \- Concatenate two strings
.SH SYNOPSIS
.B int mystrcat(char* dest, const char* src);
.SH DESCRIPTION
Appends the string src to the end of dest, adding a null terminator. Returns the new length.
.SH AUTHOR
Muneeb <muneeb@example.com>