.TH MYSTRCPY 3 "2025-09-22" "libmyutils" "Utility Functions"
.SH NAME
mystrcpy \- Copy a string
.SH SYNOPSIS
.B int mystrcpy(char* dest, const char* src);
.SH DESCRIPTION
Copies the string src to dest until the null terminator. Returns the number of characters copied.
.SH AUTHOR
Muneeb <muneeb@example.com>